name: Init project
on: create
jobs:
  init:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/templating
      - name: Set github actions[bot] as the commiter
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Git commit and push
        run: |
          git update-ref -d HEAD
          git add -A 
          git commit -m "Init" 
          git push --force
