name: Init project

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: create

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "init"
  init:
    if: github.ref_name == 'master'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Replace template variables
        run: |
          echo "Replacing $TEMPLATE with $SUBSTITUTION"
          find . -type f -not -path './\.*' -exec sed -i "s/$TEMPLATE/$SUBSTITUTION/g" {} +
          rm .github/workflows/init.yml
        env:
          TEMPLATE: project-template
          SUBSTITUTION: ${{ github.event.repository.name }}      
      - name: Reset git
        run: |
          git update-ref -d HEAD 
          git add -A 
          git commit -m "Init" 
          git push --force
